### ISSUE TITLE
Error when running "make build serve"

### ISSUE THREAD

**Issue by hungry1526** [fermyon/spin-kitchensink#17]
Hi,
I am using WSL2 to try the sample project and hit an error when building the folder. Wondering if anyone hit this before? Thanks!

![image](https://user-images.githubusercontent.com/1637753/199676089-b3c8506c-ccd2-4750-ae41-6043bfcf46eb.png)

**Comment by itowlson** [comment]
Thanks for catching this!  `spin-kitchensink` is, I'm afraid, rather out of date - it dates from before Spin 0.1, and the SDK is now at 0.6 rather than the super-preview version we used for those examples.  I'm not sure why it's failing but those SDK versions would no longer work anyway I think.

For now, I'd suggest creating your own samples from a template (`spin new`).  We'll try to get this updated but if there are particular samples you're interested in then we can help you with those for sure!
